/* Copyright (C) 1993 by Zardoz Software, Inc. */
#pragma Off (List)
/*******************************************************************************
* FILE NAME:   STDBOOL.h
*
* TITLE:       This function prototypes and data type definitions for the Wide Characters Functions.
*
*  DATA_RIGHTS: Western Design Center and R & C Services Proprietary
*               Copyright(C) 1980-2004
*               All rights reserved. Reproduction in any manner, 
*               in whole or in part, is strictly prohibited without
*               the prior written approval of R & C Services or 
*               Western Design Center.
*
* DESCRIPTION: This file describes function prototypes and data type
*              definitions used for Wide Character functions.
*
*
* SPECIAL CONSIDERATIONS:
*	        <None>
*
* AUTHOR:      R. Greenthal
*
*
* CREATION DATE:  March 17,2004
*
* REVISION HISTORY
*    Name           Date         Description
*    ------------   ----------   ----------------------------------------------
*    R. Greenthal   03/15/2004   Initial
*                   0x/xx/2004	 Added 
*
*******************************************************************************
*/

#ifndef _STDBOOL_H
#define _STDBOOL_H


/*
 *=========================== CONSTANTS & MACROS ===============================
 */

typedef int	_Bool;			/* not built into pre-C99 compilers */

#define	bool				_Bool
#define	true				1
#define	false				0
#define	__bool_true_false_are_defined	1



/*
 *============================= FUNCTION CALL PROTOTYPES ============================
 */









#endif /* End of _STDBOOL_H */
#pragma Pop (List)

/**************************************
	End of File STDBOOL.H
***************************************/
